### ISSUE TITLE
2020.10.1a: A lesson in turning adversaries into allies | Leah Garcés

### ISSUE THREAD

**Issue by shanuan** [littleflute/newTed#152]
https://www.youtube.com/watch?v=kmIZeEu-3CY&t=410s
https://www.yout.com/watch?v=kmIZeEu-3CY&t=410s

**Comment by shanuan** [comment]
把对手变成盟友的教训

**Comment by littleflute** [comment]
Transcript


00:00
Transcriber: Ivana Korom Reviewer: Joanna Pietrulewicz
00:13
In the summer of 2014,
00:16
I found myself sitting across from a man
00:19
who, by every definition, was my enemy.
00:24
His name was Craig Watts,
00:26
and he's a chicken factory farmer.
00:28
My career is devoted to protecting farmed animals
00:32
and ending factory farming.
00:35
And up until this point in my life,
00:37
I had spent every waking moment
00:41
standing up against everything this man stood for,
00:43
and now, I was in his living room.
00:47
The day I met Craig Watts
00:50
he had been raising chickens for 22 years
00:52
for a company called Perdue,
00:54
the fourth largest chicken company in the entire country.
00:58
And as a young man,
00:59
he had yearned for this way to stay on the land
01:03
in one of the poorest counties in the state.
01:06
So when the chicken industry came to town,
01:08
he thought, "This is a dream come true."
01:11
He took a quarter of a million dollar loan out,
01:14
and he built these chicken houses.
01:17
Perdue would give him a flock, he'd raise them,
01:19
and each flock he'd get paid,
01:21
and then he'd pay off in small increments that loan,
01:23
like a mortgage.
01:25
But pretty soon, the chickens got sick.
01:29
It's a factory farm, after all,
01:31
there are 25,000 chickens
01:33
that are stuffed wall-to-wall,
01:35
living on their own feces, breathing ammonia-laden air.
01:39
And when chickens get sick, some of them die.
01:42
And you don't get paid for dead chickens,
01:45
and Craig started to struggle to pay off his loan,
01:47
he realized he made a mistake,
01:49
but he was all but an indentured servant at this stage.
01:53
When I met him, he was at a breaking point.
01:58
The payments seemed never-ending.
02:00
As did the death,
02:02
despair and illness of his chickens.
02:07
Now, if we humans tried to think of some super unjust,
02:14
unfair, filthy and cruel food system,
02:17
we could not have thought of anything worse than factory farming.
02:21
Eighty billion farmed animals around the world annually
02:26
are raised and slaughtered.
02:27
They're stuffed in cages and warehouses never to see the light of day.
02:32
And that's not just a problem for those farmed animals.
02:36
Animal agriculture,
02:37
it accounts for more greenhouse gas emissions
02:40
than all of the planes, trains and automobiles put together.
02:45
And one third of our arable land is used
02:48
to grow feed to feed factory-farmed animals,
02:51
rather than ourselves.
02:53
And all that land is sprayed with immeasurable chemicals.
02:56
And ecologically important habitats,
03:00
like the Amazon,
03:02
are cut down and are burnt,
03:04
all so we can feed and house farmed animals.
03:08
By the time my three kids grow up,
03:11
there's very unlikely to be polar bears,
03:14
Sumatran elephants, orangutans.
03:17
In my lifetime,
03:19
the number of birds, amphibians, reptiles and mammals has halved.
03:25
And the main culprit
03:27
is our global appetite for meat, dairy and eggs.
03:32
And for me, up until this point,
03:34
the villain was Craig Watts.
03:39
And as I sat there in his living room,
03:41
my fear and my anger turned into something else.
03:47
Shame.
03:49
My whole life I had spent blaming him,
03:51
hating him,
03:53
I even wished him ill.
03:55
I had never once
03:58
thought about his struggle, his choices.
04:02
Could he be a potential ally?
04:05
I never had thought
04:07
he feels as trapped as the chickens.
04:12
So we had been sitting there for hours
04:14
and the midday turned into afternoon,
04:18
turned into dusk, turned into darkness,
04:19
and he suddenly said,
04:21
"OK, are you ready to see the chickens?"
04:24
So under the cover of darkness,
04:26
we walked towards one of these long, gray houses.
04:29
And he swung open the door
04:32
and we stepped inside,
04:33
and we were hit with this overpowering smell
04:37
and every muscle in my body tensed up
04:39
and I coughed and my eyes teared.
04:42
I was too overwhelmed by my own physical discomfort,
04:45
I didn't even look around at first,
04:47
but when I did,
04:48
what I saw brought me to tears.
04:51
Tens of thousands of newly hatched chicks
04:55
in this darkened warehouse
04:58
with nowhere to go and nothing to do.
05:01
Over the next few months, I returned many times,
05:05
with filmmaker Raegan Hodge,
05:07
to record, to understand,
05:09
to build trust with Craig.
05:11
And I walked his houses with him
05:13
as he picked up dead and dying birds,
05:15
birds with messed-up legs and trouble breathing
05:19
and difficulty walking.
05:20
And all of this we caught on film.
05:24
And then we decided to do something
05:27
I don't think either he or I ever expected to do when we first met.
05:30
We decided to release that footage.
05:32
And that was really risky for both of us.
05:34
It was risky for him because he could lose his income,
05:37
his home, his land, his neighbors hating him.
05:42
And I could risk getting my organization sued,
05:45
or being the reason that he would lose everything,
05:47
but we had to do it anyway.
05:53
"The New York Times" broke the story
05:56
and within 24 hours,
05:58
a million people had seen our video.
06:02
It went viral by every definition,
06:04
and suddenly we had this global platform
06:08
for talking about factory farming.
06:12
And working with Craig got me thinking.
06:16
What other unlikely allies are out there?
06:21
What other progress,
06:22
what other lessons can I learn if I cross those enemy lines?
06:28
The first lesson I learned
06:31
is that we have to become comfortable with being uncomfortable.
06:36
Only talking to people who agree with us,
06:38
it's not going to get us to the solution.
06:42
We have to be willing to enter other people's space.
06:46
Because quite often,
06:48
the enemy has the power to change the problem
06:52
that we're trying to solve.
06:53
In my case, I'm not in charge of a single chicken.
06:57
The farmer is and so are the meat companies.
06:59
So I need to enter their space if I want to solve the problem.
07:03
And a couple of years after working with Craig,
07:06
I did something again I never expected to do.
07:08
I sat down with an even bigger so-called enemy:
07:12
Jim Perdue himself.
07:14
The man I had made the villain of my viral video.
07:19
And again, through difficult conversations
07:22
and being uncomfortable,
07:25
Perdue came out with the first animal care policy
07:27
of any poultry company.
07:31
In it, they agreed to do
07:33
some of the things we had criticized them for not doing in the viral video,
07:36
like put windows into houses.
07:39
And pay for them.
07:42
And that was a really important lesson for me.
07:46
The second lesson
07:48
is that when we sit down to negotiate
07:52
with the enemy,
07:54
we need to remember, there's a human being in front of us
07:57
that very likely has more in common with us
08:01
than we care to admit.
08:03
And I learned this firsthand
08:05
when I was invited to visit at a major poultry company's headquarters.
08:09
And it was the first time that my organization had been invited,
08:13
and any organization had been invited, to visit with them.
08:17
And as we walked through the corridor,
08:20
there were literally people who were peeking our from the cubicles
08:23
to get a quick look at what does an animal rights activist look like,
08:26
and we walked --
08:27
I look like this, so I don't know what they were expecting.
08:30
(Laughter)
08:31
But as we walked into the boardroom,
08:35
there was an executive who was in charge, sitting there.
08:38
And his arms were crossed
08:40
and he did not want me to be there.
08:42
And I flipped open my laptop,
08:44
and my background photo came up,
08:46
and it was a picture of my three kids.
08:49
My daughter clearly looks different than my sons.
08:52
And when he saw that photo he uncrossed his arms
08:56
and he tilted his head and he leaned forward and he said,
08:59
"Are those your kids?"
09:01
And I said, "Yeah.
09:02
I just got back from adopting my daughter -- "
09:05
And I babbled on way too much for a professional meeting.
09:08
And he stopped me and he said,
09:11
"I have two adopted kids."
09:15
And for the next 20 minutes,
09:18
we just talked about that.
09:20
We talked about adoption and being a parent
09:22
and in those moments,
09:25
we forgot who we were supposed to be
09:28
at that table.
09:30
And the walls came down,
09:32
and a bridge was built and we crossed this divide.
09:35
And more progress was made with that company
09:39
because of that human connection that we made.
09:44
My last lesson for you
09:46
is that when we sit down with the so-called enemy,
09:50
we need to look for the win-win.
09:53
Instead of going in with farmers like Craig Watts
09:56
and thinking, "I need to put them out of farming,"
09:58
I started to think how can I help them be different kinds of farmers,
10:02
like, growing hemp or mushrooms.
10:05
And a farmer I later worked with did exactly that.
10:10
He did do the exposé with me and filmed,
10:13
and we went with "The New York Times" again,
10:15
but he went beyond that.
10:16
He quit chicken factory farming,
10:18
and it turns out
10:20
that those big, long, gray warehouses
10:22
are the perfect environment
10:25
for growing something else.
10:27
(Laughter)
10:31
(Applause)
10:35
That's hemp, people, that's hemp.
10:37
(Laughter)
10:42
Here is an environmentally friendly way to stay on the land,
10:47
to pay the bills,
10:49
that a vegan animal rights activist
10:51
and a chicken farmer can get behind.
10:53
(Laughter)
10:57
And instead of thinking,
10:59
how can I get these big meat companies out of business,
11:03
I started thinking, how can I help them evolve into a different kind of business.
11:07
One where the protein doesn't come from slaughtered animals,
11:10
but rather, plants.
11:12
And believe it or not,
11:13
these big companies are starting to move their ships in that direction.
11:18
Cargill and Tyson and Perdue are adding plant-based proteins
11:23
into their supply chain.
11:26
And Perdue himself said that,
11:29
"Our company is a premium protein company,
11:31
and nothing about that says that it has to come from animals."
11:35
And in my own home town of Atlanta,
11:39
KFC did a one-day trial with Beyond Meat,
11:42
for plant-based chicken nuggets.
11:45
And it was insane,
11:46
there were lines wrapped around the corner,
11:48
there was traffic stopped in all directions,
11:51
you would think they were giving out free Beyoncé tickets.
11:53
People are ready for this shift.
11:59
We need to build a big tent
12:01
that everyone can get under.
12:03
From the chicken factory farmer,
12:06
to the mega meat company,
12:08
to the animal rights activist.
12:10
And these lessons,
12:12
they can apply to many causes,
12:14
whether it be with a problem with an ex,
12:18
a neighbor or an in-law.
12:22
Or with some of the biggest problems of exploitation and oppression,
12:27
like factory farming,
12:29
or misogyny or racism or climate change.
12:35
The world's smallest and biggest problems,
12:39
they won't be solved by beating down our enemies
12:41
but by finding these win-win pathways together.
12:46
It does require us
12:49
to let go of that idea of us versus them
12:54
and realize there's only one us,
12:58
all of us,
12:59
against an unjust system.
13:02
And it is difficult,
13:04
and messy, and uncomfortable.
13:07
But it is critical.
13:10
And maybe the only way
13:13
to build that compassionate food system
13:16
that we all, from the chicken to the chicken farmer
13:20
to the mega meat company, to all of us,
13:23
deserve.
13:26
Thank you.
13:27
(Applause)

**Comment by littleflute** [comment]
Transcript


00:00
翻译人员: Bill Fu 校对人员: Lark Yu
00:13
2014 年的夏天，
00:16
我和一个男人面对面坐着，
00:19
用任何标准界定， 他都是我的敌人。
00:24
他叫克雷格·瓦茨 （Craig Watts），
00:26
是一名养鸡场的农场主。
00:28
而我的工作则是 致力于保护养殖动物，
00:32
并终结工厂化养殖。
00:35
而一直以来，
00:37
我把清醒的每分每秒都用来
00:41
反对这个男人所支持的一切，
00:43
而现在，我就在他家的客厅。
00:47
在遇见我之前， 克雷格·瓦茨（Craig Watts）
00:50
一直为一个名叫 柏杜（Perdue）的公司养鸡，
00:52
已经长达 22 年，
00:54
这是一家全国第四大养鸡公司。
00:58
而作为一个年轻人，
00:59
他渴望找到一种 扎根这片土地的方法，
01:03
这里是该州最贫困的县之一。
01:06
所以当养鸡公司 来到这个镇的时候，
01:08
他觉得“梦想成真”了。
01:11
他借了 25 万美元的贷款
01:14
来建造鸡舍。
01:17
柏杜每次给他一群雏鸡， 他把雏鸡养大，
01:19
然后按批获得报酬，
01:21
然后再一点点付清贷款，
01:23
就像按揭一样。
01:25
但是没过多久，鸡得病了。
01:29
毕竟这是养殖工厂，
01:31
25000 只鸡
01:33
塞满了整个鸡舍，
01:35
生活在它们自己的排泄物之上， 呼吸着充满粪便臭味儿的空气。
01:39
一旦有鸡生病， 其中一些就会死去，
01:42
而死掉的那部分则血本无归。
01:45
于是克雷格开始拼命偿还贷款，
01:47
他意识到自己犯了一个错误，
01:49
但现阶段， 他只是个签了契约的服务方。
01:53
在我见到他的时候， 他已经处在破产边缘了，
01:58
待付款项似乎和鸡的死亡、
02:00
绝望，还有疾病一样，
02:02
永远没有尽头。
02:07
现在要人类想出 一个特别不公平的、
02:14
肮脏、残酷的食物系统，
02:17
没有比工厂化养殖更糟糕的了。
02:21
每年，全世界有 800 亿只养殖动物
02:26
被豢养并屠杀。
02:27
它们被塞在笼子 和仓库中不见天日。
02:32
而这种现象不仅仅 存在于动物养殖业。
02:36
畜牧业
02:37
排放的温室气体
02:40
比所有飞机、火车 和汽车排放的总和还多。
02:45
而三分之一的可耕土地被用来
02:48
种植饲料喂养工厂的养殖动物，
02:51
而不是供养人类。
02:53
这些土地都被喷洒了 无法计量的化学物质。
02:56
那些生态栖息地，
03:00
像亚马逊，
03:02
也被无情地乱砍滥伐和焚烧，
03:04
以用来喂养和圈养家畜动物。
03:08
等我的 3 个孩子长大了，
03:11
很可能就没有北极熊、
03:14
苏门答腊大象，和红毛猩猩了。
03:17
在我的有生之年，
03:19
鸟类、两栖类、爬行类， 和哺乳类动物的数量已经减半了。
03:25
而罪魁祸首
03:27
就是全球对于肉类、奶制品 和蛋类食品的需求。
03:32
而在这一刻，对我来说，
03:34
克雷格·瓦茨就是那个恶人。
03:39
而当我坐在他家客厅的时候，
03:41
恐惧和愤怒则转变成了 另一种情感——
03:47
羞愧。
03:49
我始终都在指责他，
03:51
厌恶他，
03:53
我甚至希望他生病。
03:55
但我从未思考过
03:58
他经历的挣扎和选择。
04:02
他会是一个潜在的盟友吗？
04:05
我从来没有想过
04:07
他就和他的鸡一样 陷入了困境。
04:12
我们促膝长谈了好几个小时，
04:14
从中午到下午，
04:18
然后到黄昏，再到夜幕降临，
04:19
他突然提议：
04:21
“好，你准备好去看那些鸡了吗？”
04:24
所以在夜色笼罩下，
04:26
我们走向一栋很长的灰色房子。
04:29
他打开了门，
04:32
我们走了进去，
04:33
一股强烈的刺鼻气味 立刻扑面而来，
04:37
我浑身肌肉紧绷，
04:39
一边咳嗽一边流泪。
04:42
身体的不适反应 让我无所适从，
04:45
以至于我一开始 都无暇顾及周围的景象，
04:47
但当我回过神来，
04:48
面前的景象 让我不禁潸然泪下。
04:51
上万只新孵出的小鸡
04:55
身处昏暗的仓库里，
04:58
无处可去、无所事事。
05:01
在接下来的几个月， 我多次返回，
05:05
和电影制片人 雷根·霍奇 （Raegan Hodge）一起，
05:07
去记录，去理解，
05:09
并与克雷格建立信任。
05:11
我和他一起去往仓库，
05:13
看他捡起已死去 和垂死挣扎的小鸡，
05:15
有些鸡腿有问题， 有的呼吸困难，
05:19
还有的不能正常走路。
05:20
我们把所有这些 都记录在了影片里。
05:24
然后我们决定要做些什么，
05:27
我们第一次见面的时候 应该都没想过会这么做。
05:30
我们决定公开这部影片。
05:32
这对我们双方来说 风险都很高。
05:34
因为他有可能会失去收入，
05:37
失去家和土地， 而他的邻居们会嫉恨他。
05:42
而我所在的组织可能会被起诉，
05:45
这甚至会成为 让他失去一切的根源，
05:47
但我们义无反顾地这么做了。
05:53
《纽约时报》报导了这件事，
05:56
而且在 24 小时之内，
05:58
就有 100 万人 看过了我们的视频。
06:02
这段视频很快就火了起来，
06:04
突然间，我们就有了 这么一个全球性平台
06:08
讨论工厂化养殖。
06:12
而和克雷格一起工作的经历 让我开始思考:
06:16
周围还有多少似乎不太可能 成为盟友的人？
06:21
如果越过敌我线，
06:22
还有其他什么进展 和经验可以学习吗？
06:28
我学到的第一条经验就是，
06:31
要走出舒适圈。
06:36
只和与我们有相同看法的人交谈，
06:38
是不会让我们得到解决方案的。
06:42
我们必须愿意去涉足他人的领域。
06:46
因为通常情况下，
06:48
“敌人”才有能力去解决
06:52
我们想要解决的问题。
06:53
在我的案例中， 我不掌管哪怕一只饲养鸡。
06:57
权利都在养鸡人 和肉类企业手中。
06:59
所以如果我想要解决问题， 就需要涉足他们的领域。
07:03
在我和克雷格 一起工作了几年之后，
07:06
我又做了一件我未曾意料的事。
07:08
我和一个更大的， 所谓的“敌人”坐在了一起：
07:12
吉姆·珀杜（Jim Perdue） 本人。
07:14
在视频里被我当作恶人的那个男人。
07:19
经过又一次
07:22
令人坐卧不安的艰难对话后，
07:25
柏杜提出了家禽业有史以来的
07:27
第一个动物关爱政策。
07:31
他们同意去做
07:33
在视频中我们指责他们 没有做到的一些事项，
07:36
像是在仓库里安装窗户等，
07:39
并支付这笔投入。
07:42
那是我人生的重要一课。
07:46
第二条经验是，
07:48
当我们坐下来和敌人
07:52
交涉的时候，
07:54
要记住，我们面前的也是人，
07:57
而且他和我们之间的共同点
08:01
要比我们愿意承认的还多。
08:03
而我是在被邀请
08:05
参观一家大型家禽企业总部时 领悟到这一点的。
08:09
这也是我所在的机构 首次被邀请，
08:13
我们也是第一个 被他们邀请参观的组织。
08:17
当我们经过走廊的时候，
08:20
真的有人从隔间里伸出头来偷看，
08:23
看看动物权利活动家 到底长什么样，
08:26
然后我们往前走——
08:27
我就长这样，我不知道 他们想象的是什么样。
08:30
（笑声）
08:31
但是当我们走进会议室，
08:35
有一名主管正坐在那儿。
08:38
他双臂交叉，
08:40
看起来并不想见到我。
08:42
我打开笔记本电脑，
08:44
屏幕背景亮了起来，
08:46
是我 3 个孩子的照片。
08:49
我女儿明显看起来 和儿子们不一样。
08:52
当他看到照片的时候 就松开了交叉的手臂，
08:56
歪了歪头，探身问道：
08:59
“他们都是你的孩子吗？”
09:01
我说：“是啊。
09:02
我刚办完 领养女儿的手续回来——”
09:04
然后我就在这个正式会议上 闲扯了半天。
09:08
他叫停了我，说道：
09:11
“我也领养了两个孩子。”
09:15
在接下来的 20 分钟里，
09:18
我们就只是在聊这个话题。
09:20
聊领养孩子和怎么当一个家长，
09:22
而在那些时刻，
09:25
我们全然忘记了 自己在那张桌子前
09:28
所代表的身份。
09:30
而横亘在我们之间的墙 轰然倒塌，
09:32
一座连接之桥拔地而起， 让我们跨越了分歧。
09:35
我们和那家企业之间 有了巨大的进展，
09:39
这都要归功于我们之间 所建立的情感连接。
09:44
最后一条我想要分享的经验，
09:46
就是当我们和所谓的“敌人” 坐到一起的时候，
09:50
需要寻找一个双赢结果。
09:53
与克雷格·瓦茨这样的养殖人
09:56
持有的“我要把他们 赶出养殖业”的看法不同，
09:58
我开始思考要怎么样 帮他们成为不一样的农民，
10:02
像是种植麻类植物或者菌类。
10:05
而我之后遇到的一个农民 刚好就是这么做的。
10:10
他和我一起拍摄了纪实影片，
10:13
我们又找到《纽约时报》，
10:15
但他又更进了一步。
10:16
他退出了养鸡业，
10:18
然后却发现
10:20
那些又大又长的灰色仓库
10:22
也能是种植其他作物的
10:25
完美场所。
10:27
（笑声）
10:31
（鼓掌）
10:35
就是大麻，各位。
10:37
（笑声）
10:42
这是一个对环境有益、 留住土地的方式，
10:47
可以解决生活开支，
10:49
是一个素食和动物权利活动家
10:51
以及一个养鸡人力所能及的。
10:53
（笑声）
10:57
比起思考，
10:59
怎么让这些 大型肉类企业停止经营，
11:03
我更应该思考 怎么帮他们实现业务转型。
11:07
不是通过宰杀动物 来获取蛋白质，
11:10
而是从植物获取。
11:12
而且无论你相信与否，
11:13
这些大企业正在往那个方向探索。
11:18
嘉吉（Cargill）公司、泰森（Tyson）食品 和柏杜农场正在把植物蛋白
11:23
添加到他们的供应链之中。
11:26
而柏杜本人也说过：
11:29
“我们是一家提供 优质蛋白质的公司，
11:31
但并没有声称必须来自动物。”
11:35
而在我的家乡亚特兰大，
11:39
肯德基和 Beyond Meat 公司合作
11:42
推出了植食鸡块的一日试营业。
11:45
群众的反应简直太疯狂，
11:46
等待的队伍一直排到角落，
11:48
各个方向交通严重堵塞。
11:50
你们可能会以为他们 在免费发放碧昂斯演唱会的门票。
11:53
人们已经准备好面对转变。
11:59
我们需要建立一个
12:01
能容纳所有人的巨型平台。
12:03
从工厂养鸡人，
12:06
到大型肉类企业，
12:08
再到动物权利活动家。
12:10
而这些经验教训
12:12
可以应用到各个方面，
12:14
不管是和前任、邻居，
12:18
还是和配偶、家人间的矛盾。
12:22
又或者是某个有关 严重剥削和压迫的问题，
12:27
诸如工业化养殖、
12:29
厌女症、种族歧视，或气候变化。
12:35
这个世界上大大小小的难题，
12:39
都不是通过打败对手得到解决的，
12:41
而是要通过共同寻找 实现双赢的途径。
12:46
这就需要我们
12:49
不把自己和对方放在对立面，
12:54
并意识到我们都属于同一边，
12:58
我们所有人要
12:59
共同对抗一个不公平的系统。
13:02
这很困难，
13:04
很麻烦，很棘手。
13:07
但至关重要。
13:10
而且这可能是
13:13
建立富有同理心的 食品系统的唯一方式，
13:16
一个从鸡到养鸡人，
13:20
到巨型肉类企业， 再到我们所有人，
13:23
都值得拥有的系统。
13:26
谢谢。
13:27
（掌声）

**Comment by littleflute** [comment]
https://github.com/littleflute/newTed/releases/download/20220228/a-lesson-in-turning-adversaries-into-allies-leah-garces.mp4

**Comment by littleflute** [comment]
xd
https://mp.weixin.qq.com/s/bWjY4m3VqxA6GU3wsPxhDA
